project:
  type: website
  output-dir: docs

website:
  title: "NJA Crew Information"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - duty_summary.qmd
      - sdp_awards.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full



